# Generated by Django 3.0 on 2019-12-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(help_text='Your Facebook page URL')),
                ('linkedin', models.URLField(help_text='Your Linkedin page URL')),
                ('github', models.URLField(help_text='Your Github page URL')),
                ('instagram', models.URLField(help_text='Your Instagram page URL')),
                ('twitter', models.URLField(help_text='Your Twitter page URL')),
                ('email', models.EmailField(max_length=254)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
